### ISSUE TITLE
2 devices missing

### ISSUE THREAD

**Issue by akafester** [JohanBendz/com.lidl#11]
I've got a Lidl Outdoor RGBW light: _TZ3000_utagpnzs / TS0505A

And also a single outlet from Lidl, that dosen't get recognized: _TZ3000_upjrsxh1 / TS011F
Lidl RGBW standing light bar: _TZ3210_z1vlyufu / TS0505A

The lightbar is currently on a Deconz gateway, but i can move it to Homey if needed.

If you need more info, let me know.

**Comment by JohanBendz** [comment]
Sorry for bad response.. I need an interview of a device to be able to add it, please get back with this if you are still interested in having it added. One device per issue please. Closing this issue. The outlet has been added.
