### ISSUE TITLE
Silvercrest 3 Socket Power Strip - 3 Sockets all on or off.

### ISSUE THREAD

**Issue by MarcoBannink** [JohanBendz/com.lidl#14]
I've installed a Silvercrest 3 Socket Power Strip on my Homey early 2016 version. Using the 0.22 version of the Lidl app. It created 3 tiles in the device overview as expected.

However i was surprised to see all turn on or off when i am switching 1 on or off.

**Comment by JohanBendz** [comment]
Should be fixed in upcoming uptade.
