### ISSUE TITLE
Support for Smart Motion Sensor

### ISSUE THREAD

**Issue by Zignature** [JohanBendz/com.lidl#4]
Please add support for the Smart Motion Sensor.

Model No: HG06335
![Silvercrest-(Lidl)-Smart-Motion-Sensor](https://user-images.githubusercontent.com/4068757/106388657-e1acff00-63df-11eb-9f51-7e50c77fefec.png)

**Comment by joostvkempen** [comment]
This device is already supported: https://homey.app/nl-nl/app/com.lidl/Lidl-Smart-Home/test/

(only available when Homey Firmware is updated to version 5-experimental)

**Comment by Zignature** [comment]
Ok, cool.
I'll have to check my Homey's firmware then... :)
